# Generated by Django 5.0.3 on 2024-03-25 06:41

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Car",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("name", models.CharField(max_length=255)),
                ("brand", models.CharField(max_length=255)),
                ("year", models.IntegerField()),
            ],
            options={
                "db_table": "cars",
            },
        ),
    ]
