# Generated by Django 5.0.3 on 2024-05-06 05:14

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("app", "0002_user_full_name_user_username"),
    ]

    operations = [
        migrations.CreateModel(
            name="Conversation",
            fields=[
                ("uuid", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_active", models.BooleanField(default=True)),
                ("title", models.CharField(max_length=255)),
                ("messages", models.JSONField(default=list)),
            ],
        ),
    ]
