# Generated by Django 5.0.3 on 2024-05-06 05:18

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("app", "0003_conversation"),
    ]

    operations = [
        migrations.AlterModelTable(
            name="conversation",
            table="conversation",
        ),
    ]
