# Generated by Django 5.0.3 on 2024-05-06 06:04

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("app", "0005_alter_user_username"),
    ]

    operations = [
        migrations.AddField(
            model_name="conversation",
            name="level",
            field=models.CharField(default="BEGINNER", max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="conversation",
            name="topic",
            field=django.contrib.postgres.fields.ArrayField(
                base_field=models.CharField(max_length=255), default=list, size=None
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="user",
            name="favorite_conversations",
            field=models.ManyToManyField(blank=True, related_name="users", to="app.conversation"),
        ),
        migrations.AddField(
            model_name="user",
            name="score",
            field=models.IntegerField(default=0),
        ),
    ]
