version: "3.8"


services:
  database:
    image: postgres:16.2-alpine
    container_name: hellospeak-db
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: hellospeak
    ports:
        - "5432:5432"

  redis:
    image: redis:6.2-alpine
    container_name: hellospeak-redis
    environment:
        REDIS_PASSWORD: password
    command: /bin/sh -c 'redis-server --appendonly yes --requirepass $${REDIS_PASSWORD}'
    ports:
      - "6379:6379"

  api:
    build:
      context: ..
      dockerfile: docker/dev.Dockerfile
    container_name: hellospeak-api
    volumes:
      - "../src:/app"
    ports:
      - "8000:8000"
    env_file:
      - ../.env
    depends_on:
      - database
      - redis
