version: "3.8"


services:
  database:
    image: postgres:16.2-alpine
    container_name: database
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: hellospeak
    ports:
        - "5432:5432"
